server:
  port: 10000
sidecar:
  port: 8000
eureka:
  instance:
    hostname: gateway
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
